apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    k8s-app: celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: celery-worker
  template:
    metadata:
      labels:
        k8s-app: celery-worker
    spec:
      containers:
      - name: worker
        image: gcr.io/cliu201/celery_on_gke
        imagePullPolicy: Always
        env:
        - name: REDIS_SERVER
          value: "10.36.64.19"
        command: ["celery"]
        args: ["-A", "tasks", "worker", "--loglevel=info"]
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m